version: '3'

services:

  db:
    image: postgres:alpine
    ports:
      - "5433:5433"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    command: -p 5433

  datadog:
    image: datadog/agent
    container_name: "datadog-dev-env-manager"
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=us5.datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DB_HOST: db
      DB_PORT: 5433
      DB_NAME: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      SHARE_URI: "http://localhost:8080/share"
      REDIS_STREAM_KEY: ingsis
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_STREAM_GROUP_LINT: lint-manager
    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "manager-api-dev", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'

