version: '3'

services:

  db:
    image: postgres:alpine
    ports:
      - "5433:5433"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    command: -p 5433

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      DB_HOST: db
      DB_PORT: 5433
      DB_NAME: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      SHARE_URI: "http://localhost:8080/share"