#auth0:
#  audience: https://ingsis-group-6-snippets.com
#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://dev-rjrd5i1gdszeds2w.us.auth0.com/

auth0:
  audience: ${AUTH_AUDIENCE}
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER}

logging:
  level:
    org:
      springframework:
        security: DEBUG

redis:
  stream:
    key: ${REDIS_STREAM_KEY}
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  groups:
    lint: ${REDIS_STREAM_GROUP_LINT}