name: "Continuous Deployment - DEV"
on:
  push:
    branches:
      - develop
      - dev
      - refactor_put
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Create Short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 8
      - name: aber
        run: echo ${{ secrets.TOKEN}}
      - name: aber2
        run: echo ${{ secrets.TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ingsis-group-6
          password: ${{ secrets.TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          tags: |
            ghcr.io/ingsis-group-6/snippet-manager-dev:latest
          build-args: |
            "USERNAME=${{ secrets.PUBLISH_USERNAME }}"
            "TOKEN=${{ secrets.PUBLISH_TOKEN }}"
          push: true
